apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mdvr-platform.fullname" . }}
  labels:
    {{- include "mdvr-platform.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mdvr-platform.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
